config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stumbler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%=link_to 'Stumbler', root_path %></li>
        <li><%=link_to 'Posts', root_path %></li>
        <li>About</li>
      </ul>

      <p class="sign_in">User Login</p>
    </div>

    <div id="main_content">
      <div id="header">
        <p>Posts Feed</p>
        <div class="buttons">
          <buttons class="button"><%=link_to 'Make Post', new_post_path %></buttons>
          <buttons class="button">Log Out</buttons>
        </div>
      </div>

      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: 'alert') %>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, 'error') %>  prevented this Post from saving </h2>
    <ul>
      <% @post.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>
    </ul>

  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper" >
      <h2 class="title">
        <%= link_to post.title, post_path(post) %>
      </h2>
      <p class="body"><%= truncate(post.body, length: 100)%></p>
      <p class="date">
        Created: <%= time_ago_in_words(post.created_at) %> ago
      </p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Create post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Created: <%= time_ago_in_words(@post.created_at) %> ago |
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>
</div>